OnlineCarMarket/Areas/Administrator/Models/Engines/AddEngineViewModel.cs
using OnlineCarMarket_Infastructure;
using OnlineCarMarket_Infastructure.Entities;
using System.ComponentModel.DataAnnotations;

namespace OnlineCarMarket.Areas.Administrator.Models.Engine
{
    public class AddEngineViewModel
    {
        [Required]
        public int ManifacturerId { get; set; }

        public IEnumerable<Manifacturer> Manifacturers { get; set; } = new List<Manifacturer>();


        [Required]
        public int TypeId { get; set; }

        public IEnumerable<EngineType> Types { get; set; } = new List<EngineType>();

        [Required]
        [Range(DataConstraints.Engine.MinHorsePower, DataConstraints.Engine.MaxHorsePower)]
        public int Power { get; set; }

        [Required]
        [Range(DataConstraints.Engine.MinVolume, DataConstraints.Engine.MaxVolume)]
        public int Volume { get; set; }

        [Required]
        [Range(DataConstraints.Engine.MinConsumption, DataConstraints.Engine.MaxConsumption)]
        public double Consumption { get; set; }

    }
}

OnlineCarMarket/Areas/Administrator/Models/Engines/EditEngineModel.cs
using OnlineCarMarket_Infastructure;
using OnlineCarMarket_Infastructure.Entities;
using System.ComponentModel.DataAnnotations;

namespace OnlineCarMarket.Areas.Administrator.Models.Engine
{
    public class EditEngineModel
    {
        public int Id { get; set; }

        [Required]
        public int ManifacturerId { get; set; }

        public IEnumerable<Manifacturer> Manifacturers { get; set; } = new List<Manifacturer>();


        [Required]
        public int TypeId { get; set; }

        public IEnumerable<EngineType> Types { get; set; } = new List<EngineType>();

        [Required]
        [Range(DataConstraints.Engine.MinHorsePower, DataConstraints.Engine.MaxHorsePower)]
        public int Power { get; set; }

        [Required]
        [Range(DataConstraints.Engine.MinVolume, DataConstraints.Engine.MaxVolume)]
        public int Volume { get; set; }

        [Required]
        [Range(DataConstraints.Engine.MinConsumption, DataConstraints.Engine.MaxConsumption)]
        public double Consumption { get; set; }
    }
}

OnlineCarMarket/Areas/Administrator/Models/Engines/SearchEngineByManifactureModel.cs
using OnlineCarMarket_Infastructure.Entities;
using System.ComponentModel.DataAnnotations;

namespace OnlineCarMarket.Areas.Administrator.Models.Engine
{
    public class SearchEngineByManifactureModel
    {
        [Required]
        public int ManifacturerId { get; set; }
        public IEnumerable<Manifacturer> Manifacturers { get; set; } = new List<Manifacturer>();
    }
}

OnlineCarMarket/Areas/Administrator/Models/Engines/ShowEngineModelView.cs
namespace OnlineCarMarket.Areas.Administrator.Models.Engine
{
    public class ShowEngineModelView
    {
        public int Id { get; set; }
        public string Manufacturer { get; set; } = null!;
        public string FuelType { get; set; } = null!;
        public int HorsePower { get; set; }
        public int Volume { get; set; }
        public double Consumption { get; set; }
    }
}

OnlineCarMarket/Areas/Administrator/Controllers/EngineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCarMarket.Areas.Administrator.Intefraces;
using OnlineCarMarket.Areas.Administrator.Models.Engine;
using OnlineCarMarket_Core.Interfaces;

namespace OnlineCarMarket.Areas.Administrator.Controllers
{

    [Authorize(Policy = "AdminsOnly")]
    public class EngineController : BaseController
    {

        private readonly IEngine engineService;
        private readonly ICarService carServices;

        public EngineController(
            IEngine _engineService,
            ICarService _carService)
        {
            engineService = _engineService;
            carServices = _carService;
        }

        [HttpGet]
        public async Task<IActionResult> AddNewEngine()
        {
            AddEngineViewModel engine = new AddEngineViewModel()
            {
                Manifacturers = await carServices.GetManifacturers(),
                Types = await engineService.GetEngineType()
            };

            return View(engine);
        }

        [HttpPost]
        public async Task<IActionResult> AddNewEngine(AddEngineViewModel model)
        {
            if (ModelState.IsValid)
            {
                var isThere = engineService.CheckIfEngineIsIn(model);
                if (isThere == false)
                {
                    await engineService.AddEngineAsync(model);
                    return RedirectToAction(nameof(AllEngines));
                }
                
            }

            return RedirectToAction("index", "home");
        }

        public async Task<IActionResult> AllEngines()
        {
            return View(await engineService.GetAllEngines());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            List<EditEngineModel> model = await engineService.GetTheEngineToEdit(id);
            model[0].Manifacturers = await carServices.GetManifacturers();
            model[0].Types = await engineService.GetEngineType();
            return View(model[0]);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditEngineModel model)
        {
            AddEngineViewModel model2 = new AddEngineViewModel()
            {
                Power = model.Power,
                ManifacturerId = model.ManifacturerId,
                Consumption = model.Consumption,
                TypeId = model.TypeId,
                Volume = model.Volume

            };
            if (ModelState.IsValid)
            {
                var isThere = engineService.CheckIfEngineIsIn(model2);
                if (isThere == false)
                {
                    await engineService.SaveChangesAsync(model);
                    return RedirectToAction(nameof(AllEngines));
                }
                
            }

            return RedirectToAction("index", "home");

        }

        [HttpGet]
        public async Task<IActionResult> GetAllByManifacture()
        {
            SearchEngineByManifactureModel model = new SearchEngineByManifactureModel()
            {
                Manifacturers = await carServices.GetManifacturers()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> GetAllByManifacture(SearchEngineByManifactureModel model)
        {
            var filteredcars = await engineService.searchEngineByManifacture(model);
            return View(nameof(Result), filteredcars);

        }


        public IActionResult Result(List<ShowEngineModelView> filteredcars)
        {
            return View(filteredcars);
        }
    }

}

OnlineCarMarket/Controllers/EngineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using OnlineCarMarket_Core.Interfaces;
using OnlineCarMarket_Core.Models.Car;
using OnlineCarMarket_Core.Models.Engines;
using OnlineCarMarket_Core.Services.CarServ;

namespace OnlineCarMarket.Controllers
{
    
    [Authorize(Policy = "AdminsOnly")]
    public class EngineController : Controller
    {

        private readonly IEngine engineService;
        private readonly ICarService carServices;

        public EngineController(
            IEngine _engineService,
            ICarService _carService)
        {
            engineService = _engineService;
            carServices = _carService;
        }

        [HttpGet]
        public async Task<IActionResult> AddNewEngine()
        {
            AddEngineViewModel engine = new AddEngineViewModel()
            {
                Manifacturers = await carServices.GetManifacturers(),
                Types = await engineService.GetEngineType()
            };

            return View(engine);
        }

        [HttpPost]
        public async Task<IActionResult> AddNewEngine(AddEngineViewModel model)
        {
            if (ModelState.IsValid)
            {
               await engineService.AddEngineAsync(model);
            }

            return RedirectToAction(nameof(AllEngines));
        }

        public async Task<IActionResult> AllEngines()
        {
            return View(await engineService.GetAllEngines());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            List<EditEngineModel> model =  await engineService.GetTheEngineToEdit(id);
            model[0].Manifacturers = await carServices.GetManifacturers();
            model[0].Types = await engineService.GetEngineType();
            return View(model[0]);
            
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditEngineModel model)
        {
            if (ModelState.IsValid)
            {
                await engineService.SaveChangesAsync(model);
            }
            
            return RedirectToAction(nameof(AllEngines));

        }

        [HttpGet]
        public async Task<IActionResult> GetAllByManifacture()
        {
            SearchEngineByManifactureModel model = new SearchEngineByManifactureModel()
            {
                Manifacturers = await carServices.GetManifacturers()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> GetAllByManifacture(SearchEngineByManifactureModel model)
        {
            var filteredcars = await engineService.searchEngineByManifacture(model);
            return View(nameof(Result), filteredcars);

        }


        public IActionResult Result(List<ShowEngineModelView> filteredcars)
        {
            return View(filteredcars);
        }
    }

}

OnlineCarMarket/Areas/Administrator/Views/Engine/AddNewEngine.cshtml
@model AddEngineViewModel
@{
    ViewData["Title"] = "Add a new Engine";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h2>Add New Engine</h2>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="@Model.ManifacturerId" class="form-label">Manifacturer</label>
                <select asp-for="@Model.ManifacturerId" class="form-control">
                    @foreach (var manifacturer in Model.Manifacturers)
                    {
                        <option value="@manifacturer.Id">@manifacturer.Name</option>
                    }
                </select>
                <span asp-validation-for="ManifacturerId" class="text-danger"></span>
            </div>

            <p> </p>

            <div class="mb-3">
                <label asp-for="@Model.TypeId" class="form-label">Fuel Type</label>
                <select asp-for="@Model.TypeId" class="form-control">
                    @foreach (var fuel in Model.Types)
                    {
                        <option value="@fuel.Id">@fuel.Fuel</option>
                    }
                </select>
                <span asp-validation-for="ManifacturerId" class="text-danger"></span>
            </div>

            <p> </p>

            <div class="form-floating">
                <input asp-for="@Model.Power" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Power">Horse Power</label>
                <span asp-validation-for="@Model.Power" class="text-danger"></span>
            </div>

            <p> </p>
            

            <div class="form-floating">
                <input asp-for="@Model.Volume" class="form-control" autocomplete="" aria-required="true" />
                <label asp-for="@Model.Volume">Volume</label>
                <span asp-validation-for="@Model.Volume" class="text-danger"></span>
            </div>
            <p> </p>

            <div class="form-floating">
                <input asp-for="@Model.Consumption" class="form-control" autocomplete="" aria-required="true" />
                <label asp-for="@Model.Consumption">Consumption</label>
                <span asp-validation-for="@Model.Consumption" class="text-danger"></span>
            </div>
          
            

            <p> </p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Add Engine</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OnlineCarMarket/Areas/Administrator/Views/Engine/AllEngines.cshtml
@model List<ShowEngineModelView>

@{
    ViewData["Title"] = "Engines";
}

<div class="text-center">
    <h3>All Engines</h3>
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
</div>

<a class="nav-link text-dark text-center" asp-area="Administrator" asp-controller="Engine" asp-action="AddNewEngine">New Engine</a>
<a class="nav-link text-dark text-center" asp-area="Administrator" asp-controller="Engine" asp-action="GetAllByManifacture">Select engines by brand</a>

<div class="text-center row">

    @foreach (var car in Model)
    {
        <div class="card col-4" style="width: 20rem;">
            <div class="card-body, bg-warning text-black">
                <p class="mb-0">Manufacturer: @car.Manufacturer</p>
                <p class="mb-0">Fuel: @car.FuelType</p>
                <p class="mb-0">Horse Power: @car.HorsePower</p>
                <p class="mb-0">Cubic Capacity: @car.Volume</p>
                <p class="mb-0">Fuel Consumption: @car.Consumption</p>
            </div>
            <p></p>
            <div class="text-center">
                <a asp-controller="Engine" asp-action="Edit" asp-route-id="@car.Id" class="btn btn-success">Edit</a>
            </div>
        </div>
    }
</div>

OnlineCarMarket/Areas/Administrator/Views/Engine/Edit.cshtml
@model EditEngineModel
@{
    ViewData["Title"] = "Change Engine";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h2>Change Engine</h2>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <label asp-for="@Model.ManifacturerId" class="form-label">Manifacturer</label>
                <select asp-for="@Model.ManifacturerId" class="form-control">
                    @foreach (var manifacturer in Model.Manifacturers)
                    {
                        <option value="@manifacturer.Id">@manifacturer.Name</option>
                    }
                </select>
                <span asp-validation-for="ManifacturerId" class="text-danger"></span>
            </div>

            <p> </p>

            <div class="mb-3">
                <label asp-for="@Model.TypeId" class="form-label">Fuel Type</label>
                <select asp-for="@Model.TypeId" class="form-control">
                    @foreach (var fuel in Model.Types)
                    {
                        <option value="@fuel.Id">@fuel.Fuel</option>
                    }
                </select>
                <span asp-validation-for="ManifacturerId" class="text-danger"></span>
            </div>

            <p> </p>

            <div class="form-floating">
                <input asp-for="@Model.Power" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Power">Horse Power</label>
                <span asp-validation-for="@Model.Power" class="text-danger"></span>
            </div>

            <p> </p>


            <div class="form-floating">
                <input asp-for="@Model.Volume" class="form-control" autocomplete="" aria-required="true" />
                <label asp-for="@Model.Volume">Volume</label>
                <span asp-validation-for="@Model.Volume" class="text-danger"></span>
            </div>
            <p> </p>

            <div class="form-floating">
                <input asp-for="@Model.Consumption" class="form-control" autocomplete="" aria-required="true" />
                <label asp-for="@Model.Consumption">Consumption</label>
                <span asp-validation-for="@Model.Consumption" class="text-danger"></span>
            </div>



            <p> </p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Save</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OnlineCarMarket/Areas/Administrator/Views/Engine/GetAllByManifacture.cshtml
@model SearchEngineByManifactureModel

@{
    ViewData["Title"] = "Search for car/s by Brand";
}


<div class="text-center">
    <h3>Search for car/s by Brand</h3>
</div>


<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h3>Search your car.</h3>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="mb-3">
                <p></p>
                <p></p>
                <label asp-for="@Model.ManifacturerId" class="form-label">Select Brand</label>
                <select asp-for="@Model.ManifacturerId" class="form-control">
                    @foreach (var manifacturer in Model.Manifacturers)
                    {
                        <option value="@manifacturer.Id">@manifacturer.Name</option>
                    }
                </select>
                <span asp-validation-for="ManifacturerId" class="text-danger"></span>
            </div>


            <p> </p>
            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Search</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OnlineCarMarket/Areas/Administrator/Views/Engine/Result.cshtml
@model List<ShowEngineModelView>

@{
    ViewData["Title"] = "Engines";
}

<div class="text-center">
    <h3>Engines</h3>
</div>



<div class="text-center row">

    @foreach (var car in Model)
    {
        <div class="card col-4" style="width: 20rem;">
            <div class="card-body, bg-warning text-black">
                <p class="mb-0">Manufacturer: @car.Manufacturer</p>
                <p class="mb-0">Fuel: @car.FuelType</p>
                <p class="mb-0">Horse Power: @car.HorsePower</p>
                <p class="mb-0">Cubic Capacity: @car.Volume</p>
                <p class="mb-0">Fuel Consumption: @car.Consumption</p>
            </div>
            <p></p>
            <div class="text-center">
                <a asp-controller="Engine" asp-action="Edit" asp-route-id="@car.Id" class="btn btn-success">Edit</a>
            </div>
        </div>
    }
</div>