OnlineCarMarket/Areas/Administrator/Controllers/ManifacturerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCarMarket.Areas.Administrator.Intefraces;
using OnlineCarMarket.Areas.Administrator.Models.Manufactur;
using OnlineCarMarket_Core.Interfaces;

namespace OnlineCarMarket.Areas.Administrator.Controllers
{
    [Authorize(Policy = "AdminsOnly")]
    public class ManifacturerController : BaseController
    {
        private readonly IManifacturer manifacturerService;
        private readonly ICarService carServices;

        public ManifacturerController(
            IManifacturer _manifacturerService,
            ICarService _carService)
        {
            manifacturerService = _manifacturerService;
            carServices = _carService;
        }

        [HttpGet]
        public async Task<IActionResult> AddBrand()
        {

            NewManufacturerViewModel model = new NewManufacturerViewModel()
            {
                Countries = await manifacturerService.GetAllCountries()
            };

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> AddBrand(NewManufacturerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var isThere = manifacturerService.CheckIfBrandExists(model.Name);
                if (isThere == false)
                {
                    await manifacturerService.AddBrandAsync(model);
                    return RedirectToAction(nameof(AllBrands));
                };
                
            }

            return RedirectToAction("index", "home");
        }


        public async Task<IActionResult> AllBrands()
        {
            return View(await manifacturerService.GetAllBrands());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            List<EditManufacturerViewModel> toEdit = await manifacturerService.FindBrandToBeEdited(Id);
            toEdit[0].Countries = await manifacturerService.GetAllCountries();
            return View(toEdit[0]);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditManufacturerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var isThere = manifacturerService.CheckIfBrandExists(model.Name);
                if (isThere == false)
                {
                    await manifacturerService.SaveChanges(model);
                    return RedirectToAction(nameof(AllBrands));
                }
               
            }

            return RedirectToAction("index", "home");
        }



    }
}

OnlineCarMarket/Controllers/ManifacturerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCarMarket_Core.Interfaces;
using OnlineCarMarket_Core.Models.Car;
using OnlineCarMarket_Core.Models.Manufactur;
using OnlineCarMarket_Core.Services.CarServ;

namespace OnlineCarMarket.Controllers
{
    [Authorize(Policy = "AdminsOnly")]
    public class ManifacturerController : Controller
    {
        private readonly IManifacturer manifacturerService;
        private readonly ICarService carServices;

        public ManifacturerController(
            IManifacturer _manifacturerService,
            ICarService _carService)
        {
            manifacturerService = _manifacturerService;
            carServices = _carService;
        }

        [HttpGet]
        public async Task<IActionResult> AddBrand()
        {
            NewManufacturerViewModel model = new NewManufacturerViewModel()
            {
                Countries = await manifacturerService.GetAllCountries()
            };

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> AddBrand(NewManufacturerViewModel model)
        {
            if (ModelState.IsValid)
            {
                await manifacturerService.AddBrandAsync(model);
            }

            return RedirectToAction(nameof(AllBrands));
        }


        public async Task<IActionResult> AllBrands()
        {
            return View(await manifacturerService.GetAllBrands());
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            List<EditManufacturerViewModel> toEdit = await manifacturerService.FindBrandToBeEdited(Id);
            toEdit[0].Countries = await manifacturerService.GetAllCountries();
            return View(toEdit[0]);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditManufacturerViewModel model)
        {
            if (ModelState.IsValid)
            {
                await manifacturerService.SaveChanges(model);
            }
            
            return RedirectToAction(nameof(AllBrands));
        }

        

    }
}

OnlineCarMarket/Areas/Administrator/Views/Manifacturer/AddBrand.cshtml
@model NewManufacturerViewModel
@{
    ViewData["Title"] = "Add a new Brand";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h2>Add New Brand</h2>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-floating">
                <input asp-for="@Model.Name" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Name">Brand</label>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <p> </p>
            <div class="mb-3">
                <label asp-for="@Model.CountryId" class="form-label">Manifacturer</label>
                <select asp-for="@Model.CountryId" class="form-control">
                    @foreach (var country in Model.Countries)
                    {
                        <option value="@country.Id">@country.Name</option>
                    }
                </select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>

            <p> </p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Add Brand</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OnlineCarMarket/Areas/Administrator/Views/Manifacturer/AllBrands.cshtml
@model List<ShowManufacturerViewModel>

@{
    ViewData["Title"] = "Brands";
}

<div class="text-center">
    <h3>All Brands</h3>
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
</div>

<a class="nav-link text-dark text-center" asp-area="Administrator" asp-controller="Manifacturer" asp-action="AddBrand">New Brand</a>

<div class="text-center row">

    @foreach (var car in Model)
    {
        <div class="card col-4" style="width: 20rem;">
            <div class="card-body, bg-primary text-white">
                <p class="mb-0">Manufacturer: @car.Name</p>
                <p class="mb-0">Country: @car.Country</p>
            </div>
            <p></p>
            <div class="text-center">
                <a asp-controller="Manifacturer" asp-action="Edit" asp-route-id="@car.Id" class="btn btn-danger">Edit</a>
            </div>
        </div>
    }
</div>

OnlineCarMarket/Areas/Administrator/Views/Manifacturer/Edit.cshtml
@model EditManufacturerViewModel
@{
    ViewData["Title"] = "Edit Brand";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h2>Edit Brand</h2>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-floating">
                <input asp-for="@Model.Name" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Name">Brand</label>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>
            <p> </p>
            <div class="mb-3">
                <label asp-for="@Model.CountryId" class="form-label">Manifacturer</label>
                <select asp-for="@Model.CountryId" class="form-control">
                    @foreach (var country in Model.Countries)
                    {
                        <option value="@country.Id">@country.Name</option>
                    }
                </select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>

            <p> </p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Save</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}