OnlineCarMarket/Areas/Administrator/Controllers/BodyTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCarMarket.Areas.Administrator.Models.Body;
using OnlineCarMarket.Areas.Administrator.Interfaces;

namespace OnlineCarMarket.Areas.Administrator.Controllers
{
    [Authorize(Policy = "AdminsOnly")]
    public class BodyTypeController : BaseController
    {
        private readonly IBody bodyService;

        public BodyTypeController(IBody _bodyService)
        {
            bodyService = _bodyService;
        }

        [HttpGet]
        public IActionResult AddBody()
        {
            AddBodyTypeViewModel model = new AddBodyTypeViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddBody(AddBodyTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                await bodyService.AddBodyAsync(model);
            }
            return RedirectToAction("index", "home");
        }

        public async Task<IActionResult> AllBodyTypes()
        {
            return View(await bodyService.GetAllBodyTypes());
        }
    }
}

OnlineCarMarket/Controllers/BodyTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineCarMarket_Core.Models.Body;
using OnlineCarMarket_Core.Interfaces;

namespace OnlineCarMarket.Controllers
{
    [Authorize(Policy = "AdminsOnly")]
    public class BodyTypeController : Controller
    {
        private readonly IBody bodyService;

        public BodyTypeController(IBody _bodyService)
        {
            bodyService = _bodyService;
        }

        [HttpGet]
        public IActionResult AddBody()
        {
            AddBodyTypeViewModel model = new AddBodyTypeViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddBody(AddBodyTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                await bodyService.AddBodyAsync(model);
            }
            return RedirectToAction(nameof(AllBodyTypes));
        }

        public async Task<IActionResult> AllBodyTypes()
        {
            return View (await bodyService.GetAllBodyTypes());
        }
    }
}

OnlineCarMarket/Areas/Administrator/Views/BodyType/AddBody.cshtml
@model AddBodyTypeViewModel
@{
    ViewData["Title"] = "Add a new BodyType";
}

<div class="row">
    <div class="col-md-4">
        <form id="registerForm" asp-route-returnUrl="" method="post">
            <h2>Add New BodyType</h2>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-floating">
                <input asp-for="@Model.Name" class="form-control" autocomplete="model" aria-required="true" />
                <label asp-for="@Model.Name">Name</label>
                <span asp-validation-for="@Model.Name" class="text-danger"></span>
            </div>

            <p> </p>

            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Add New Body Type</button>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OnlineCarMarket/Areas/Administrator/Views/BodyType/AllBodyTypes.cshtml
@model List<ShowBodyTypes>

@{
    ViewData["Title"] = "Body Types";
}

<div class="text-center">
    <h3>All Body Types</h3>
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
</div>

 
 <a class="nav-link text-dark text-center" asp-area="Administrator" asp-controller="BodyType" asp-action="AddBody">Add New BodyType</a>


<div class="text-center row">
    
    @foreach (var car in Model)
    {
        <div class="card col-4" style="width: 20rem;">
            <div class="card-body, bg-danger text-white">
                <p class="mb-0">Type: @car.Name</p>
                
            </div>
        </div>
    }
</div>